import React from "react";
import Page from '../Page/index.js';
import './index.css';

const Introduction = () => {
    return (
        <div>
            <Page>
          
                <h1>Preface</h1>
                <p>This is the beginning of a new edition of the Book of Genesis, based on the 1917 <a href="https://jps.org/books/holy-scriptures-tanakh-1917-edition/">OJPS</a> translation and created by members of an undergraduate class in Boston University’s <a href="https://www.bu.edu/core/">Core Curriculum</a>. As with any edition, our representation of the text is shaped by the theory behind it. In brief, we believe that virtually all modern editions of Genesis ignore underlying patterns that are fundamental to the text. Specifically, we find that the standard divisions of chapter, paragraph, and verse obscure and sometimes conflict with poetic patterns that are inseparable from the words, ideas, and motifs of Genesis. By foregrounding these patterns, this edition enables readers to engage with the text in a manner that is essential to more fully appreciate its artistry and understand its meaning. While our theory is deeply indebted to the work of a range of scholars (cited in the Introductory Essay and Bibliography), our edition is, to the best of our knowledge, unique.</p>
                <p>One of the chief benefits of digital scholarly editions, as opposed to print editions, is that they permit multiple views of the text. This digital scholarly edition allows three main views:</p>
                <ul>
                    <li>A traditional view, emphasizing the chapter-paragraph-verse structure (“Chapter text”)</li>
                    <li>A view that divides the text into sections according to the underlying poetic structure as perceived by the student editors (“Chiastic text”)</li>
                    <li>And an overview of the poetic structure’s parallel units, which highlights what the parallel sections have in common and which can also function as a navigational tool (“Chiastic outline”)</li>
                </ul>
                <p>With any of the edition’s text views, there is the option to toggle on or off color coding that overlays how the Documentary Hypothesis (as formulated by Gerhard von Rad) breaks down the text, and with any view there are comment bubbles that, for selected words and passages, can be clicked to reveal transliterations of the ancient Hebrew, alternate English translations, and commentary by both the student editors and professional scholars. Finally, by selecting “Show chiastic parallel,” one can simultaneously view the full text of parallel units.</p>
                <p>Currently, the edition is limited to just the Flood story (Genesis Chapters 6-9). That is on account of the complexity and labor-intensiveness of the work, combined with the limitations of a small class of undergraduates learning and applying new concepts and methods during a single fifteen-week semester. The entire site is based on the students’ collective, semester-long analysis of Genesis, culminating in their collaborative, iterative encoding of semantic and structural features in eXtensible Markup Language (<a href="https://www.w3schools.com/xml/">XML</a>). A detailed account of this process, including a brief introduction to XML and how it can be used for the analysis of literary texts, is described in the students’ Introductory Essay, below. Here I simply wish to emphasize the potential value of this approach.</p>
                <p>When the semester began, I was confident in my understanding of the underlying structure of the Flood story. I was convinced of the analysis of Gordon J. Wenham. When some of my students questioned the central feature of Wenham’s analysis, I encouraged debate, but I did not want to waste too much time on what I believed to be a dead end. However, my students’ XML encoding had led them to focus on details of the text. The debate went on, was tabled, and was revived again near the end of the semester, when we had to arrive at a consensus if we were to publish anything. At that point, I assigned my students to re-encode the passage in question with XML, and when I sat down to compare their various analyses, in preparation for leading a class discussion on how to reconcile them, I became convinced that Wenham was wrong and the dissenting students were right. It was there in the structure of the text, as revealed by the encoding. And it was not any one student’s encoding that convinced me, but the sum of their slightly different approaches. When I shared with the class what I now saw, we all were convinced. With any luck, all teachers learn from their students. But what I learned from this class about the Flood story was a direct consequence of not only my students’ intelligence and commitment, but also the course’s methodology: iterative, collaborative close reading with XML.</p>
                <p>After the students agreed upon a single way to encode the entire Flood story, I converted their XML into <a href="https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html">TEI P5</a>, an extensive, standardized, widely used form of XML that, in turn, can be published online using various open-source software libraries. The software library used to publish this online edition is <a href="https://teic.github.io/CETEIcean/">CeTEIcean</a>, and it was implemented by a developer in accordance with the students’ overall design specifications.</p>
                <p>As I have mentioned, this edition is a work in progress. Like the student editors, who express their view in the Introductory Essay, I hope that, in future semesters, additional cohorts of Core Curriculum students will extend, revise, and complete the work we have begun.</p>
                <p>&mdash; Jason Prentice, Senior Lecturer, Boston University CAS Writing Program and Core Curriculum</p>
                <hr />
                <h1>Introductory Essay</h1>
                <p className="Introduction_byline">by the editors</p>
                <h2>A Brief History of Genesis</h2>
                <p>The book of Genesis is one of the oldest and most influential texts in the world, and it has been at the center of controversy since its inception over two millennia ago. Why was humanity exiled from Eden? What does God value? What is the purpose of our existence? While this digital scholarly edition does not presume to answer such questions, it does offer a unique, student-based perspective on what the original author(s) may have had in mind. The objective of this edition is to provide you, the reader, with a version of Genesis that allows for a deeper understanding of the text while also offering our own interpretations and insights that may be of value.</p> 
                <p>Genesis was originally written in Hebrew and is among the first five books of the Hebrew Bible, known as the Pentateuch or Torah. The Hebrew people first appeared in “the ancient Near East, particularly the Fertile Crescent region, running from the Tigris and Euphrates rivers up to Syria and down through Palestine to the Nile Delta” (“Biblical literature”). In this area, “great civilizations and empires developed and semi nomadic ethnic groups, such as the Hebrews, were involved in the mixture of peoples and cultures” (“Biblical literature”). While the exact origin of the Hebrew people is unknown, according to biblical tradition they “migrated from Mesopotamia to Canaan in the 2nd millennium BCE” and settled in modern-day Israel or Palestine (“Biblical literature”).</p> 
                <p>With respect to Genesis and all five books of the Torah, the traditional Jewish and Christian view has been that Moses was the author. However, scholarship during the 19th and 20th centuries led to a new theory known as the Documentary Hypothesis. According to this theory, the Hebrew Bible or Old Testament was written by multiple authors over a span of hundreds of years. This is based on a number of perceived discrepancies in the text, as well as differing writing styles. In Genesis, for example, Chapter One refers to God as Elohim (usually translated as “God”), while Chapter Two refers to Him as Yahweh Elohim (usually translated as “LORD God”). In the same two chapters, other perceived discrepancies include two separate creation stories, which appear to suggest two different creations of Adam and Eve, different orders of creation, and so on. While it is not certain that these perceived discrepancies result from multiple authors, multiple ‘voices’ with multiple perspectives appear to exist throughout the text.</p> 
                <p>The Documentary Hypothesis has been the leading theory about the authorship of the Torah since the 20th century. However, it has been widely rejected by most Orthodox Jews and conservative Christians, and over the last century, “an entire literature has developed within conservative scholarship and religious communities dedicated to the refutation of biblical criticism in general and of the documentary hypothesis in particular” (“Documentary hypothesis”). In the words of biblical scholar and archaeologist W. F. Albright, “even the most ardent proponents of the documentary hypothesis must admit that no tangible, external evidence for the existence of the hypothesized ‘J,’ ‘E,’ ‘D,’ ‘P’ sources exists” (“Documentary hypothesis”). Nevertheless, the general idea of the hypothesis “remains widely accepted by contemporary biblical scholars” (“Documentary hypothesis”).</p> 
                <p>For the purposes of this edition, which presents just a small portion of the Book of Genesis, we will focus on the hypothesized sources most relevant to Genesis in particular: the Yahwist and the Priestly sources. The Yahwist source is thought to be the older of the two and is dated as far back as the 10th century BCE (“Biblical literature”). In contrast, the Priestly source is believed to have been written around the 5th century BCE, roughly contemporaneous with the Babylonian Exile of the Hebrew people of the Kingdom of Judah (“Biblical literature,” “Genesis”). These tentative dates provide a framework for better understanding the apparently conflicting plot and themes of Genesis, as well as the context under which these hypothesized versions may have been written.</p> 
                <h2>A Brief History of Editions of the Text</h2>
                <p>The oldest known written versions of the Hebrew Bible are leather or papyrus scrolls, dating back as far as the 3rd century BCE (“Biblical literature”). However, the oldest complete version of Genesis is found in the Masoretic text, a version of the Hebrew Bible created by a group of Jewish scholars (the Masoretes) over a span of hundreds of years, from the 6th to 10th centuries CE. It is with the Masoretic text that Genesis became part of a book, with two covers, pages, and a spine (“Masoretic text”). This Hebrew text of Genesis was the basis for the 1917 English-language translation by the Jewish Publication Society (OJPS), which is the base text we have used for our edition (Jewish Publication Society).</p> 
                <p>Almost all modern editions of Genesis are fundamentally like the Masoretic text in that they present Genesis as a traditional sort of book, broken into chapters, which are divided into paragraphs of prose or stanzas of poetry, which are divided into lines or verses. While this may seem not worth remarking upon, Genesis was not originally a book. It may not even have originally been a scroll. The problem for modern readers is that books look familiar, and we bring to them certain assumptions that we may not be conscious of. We expect that books are meant to be read linearly, in one direction, from beginning to end. We expect most stories in books to have a logical, cause-and-effect sequence of events. We expect that chapter divisions exist to mark off distinct, unified sections of the larger text. We are used to a book having an author -- a single author. We are so accustomed to this that even when we do not know who the author was or whether there were multiple authors, we might catch ourselves talking about “the author’s intentions.” All of these habits and assumptions can get in the way of understanding a text such a Genesis, which is much older than any book. Indeed, we may be closer in time to the Medieval Masoretes than the Masoretes were to the original author or authors of Genesis.</p>
                <p>The Documentary Hypothesis encourages us to look at Genesis (and the rest of the Hebrew Bible) differently. As discussed in the first part of this introduction, this hypothesis is based in part on seeming contradictions within the “plot” of Genesis, aspects of Genesis that get in the way of a traditional, linear reading of the text as a logical cause-and-effect plot. After all, how can the world be created twice, in two different orders and two different ways? Based on such perceived discrepancies, the Documentary Hypothesis challenges the idea that Genesis stems from a single author. Similarly, this hypothesis challenges traditional chapter divisions. For example, it identifies the break between the first creation story (which it attributes to the 5th century CE Priestly source) and second creation story (which it attributes to the 10th century CE Yahwist source) as the middle of the fourth verse of Chapter 2.</p>
                <p>Based on such conclusions, a more unusual modern edition is represented by the <a href="https://en.wikiversity.org/w/index.php?title=Bible/King_James/Documentary_Hypothesis/Genesis">Bible/KingJames/DocumentaryHypothesis/Genesis</a>, a crowd-sourced digital publication by Wikipedia. While this edition maintains traditional chapter, paragraph, and verse divisions, it color-codes the text to attribute portions to the Priestly, Yahwist, and other hypothesized authorial sources. Thus, this online edition of Genesis encourages a very different sort of approach from the reader. Rather than encouraging the reader to find unity, it points toward contradictions. Rather than limiting the reader to reading from beginning to end, it encourages one to read by color -- e.g., to skip from one blue-font section to the next. That is essentially how proponents of the Documentary Hypothesis have read the Flood story: as two separate stories that can be disentangled so that they each, separately, make more sense. However, as noted earlier in this introduction, one problem with the Documentary Hypothesis is that it cannot be proven. Another problem is that it does not address the question of why none of the multiple hypothesized author-editors ever bothered to “fix” the discontinuities and contradictions.</p>
                <h2>What Makes This Edition Different</h2>
                <p>This edition of Genesis departs from both the dominant representation of Genesis as a normal book and the less common representation of it as a patchwork of many texts. Unlike previous editors, we represent Genesis according to underlying poetic structures that often conflict with both the chapter-paragraph-verse divisions of traditional Bibles and the source divisions of the Documentary Hypothesis. To date, we have finished our analysis of just a small portion of Genesis: namely, the Flood story (Chapters 6-9), which we represent as a chiasm that has smaller structures, including three smaller chiasms, nested within it.</p> 
                <p>According to John Welch, author of Chiasmus in Antiquity, a chiasm is “a two-part structure or system in which the second half is a mirror of the first, i.e. where the first term recurs last, and the last first” (10). As Welch points out, one of the more famous chiasms in the English language is by Coleridge: “Flowers are lovely, love is flowerlike” (9). In this particular example, each half of the mirror contains three parallels:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;<b>A</b> Flowers</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<b>B</b> are</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<b>C</b> lovely,</p> 
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<b>C’</b> love</p> 
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<b>B’</b> is</p> 
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<b>A’</b> flowerlike</p>
                <p>While chiasms are rare in English-language literature, they are frequently found in ancient texts, including The Odyssey and Euripides’ Orestes, as well as in the Bible (Welch 14). In these ancient texts, the parallels or “double structures” may have aided in the oral transmission of these texts before they were written down (Welch 12). Additionally, they exhibit what Welch calls “moral implications”: chiasms encourage readers to cross-check parallel sections of a text, comparing mirrored sections that showcase either similarities or stark differences, ultimately guiding readers to interpretations that might not result from a purely linear reading (12). In other words, awareness of a chiastic structure leads to a different, non-linear reading of a text.</p>
                <p>This is not to say that all chiasms are purposeful; some may be accidental (Welch 14). However, as we hope to demonstrate through this edition, the chiasm that encompasses the Flood story seems to be clearly intentional, and recognizing this structure changes the way we interact with the text. Unlike traditional chapter-paragraph-verse representations of the story, which find unity in plot, our edition finds unity in multiple and sometimes nested parallel structures. Unlike the Documentary Hypothesis edition, our representation of the Flood chiasm encourages readers to view the text as an intricate and artistically unified whole.</p> 
                <h2>Methodology</h2>
                <p>This edition is the product of a group of undergraduate students from Boston University enrolled in <a href="https://www.bu.edu/core/academics/courses/">CC 320: Extended Multimedia Encounters with Core Texts</a>. This course is part of BU’s <a href="https://www.bu.edu/core/">Core Curriculum</a>, a program that invites students to engage critically with foundational <a href="https://www.bu.edu/core/books/">“Core texts,”</a> primarily in the humanities and social sciences. CC 320 is an elective that allows students to further engage with a specific text and build upon their previous knowledge. The primary goal is to have students reimagine a Core text in a digital format and conclude with a collaborative final project that will be available to other students. The Fall 2020 section of CC 320 consisted of nine students, each with different levels of familiarity with the Book of Genesis: some had previously studied it in Core, others knew of it from outside study, and others were unfamiliar with the text. We met for an hour and fifteen minutes twice a week from September to December. All meetings were held over Zoom conference calls due to the COVID-19 pandemic.</p>
                <p>As previously mentioned, our base text was the 1917 Jewish Publication Society (OJPS) translation of Genesis. We chose this translation because it is relatively literal and because it is in the public domain (and therefore could be republished by us).</p>
                <p>We began our analysis by doing a traditional close reading of each chapter, followed by a class discussion. We separated the chapters into sections based on the overarching story, beginning with the creation stories, then Adam and Eve, and so on. To facilitate collaborative annotation and online discussion, each chapter was on a separate Google doc in our shared class drive.  When annotating, we made comments on anything we deemed important and raised questions that led to in-depth discussions and different interpretations. The instructor provided annotations with alternate translations and transliterations of the original Hebrew. This traditional close reading was supplemented by multiple secondary sources, such as St. Augustine’s interpretations of Genesis Chapter 3 and Michael Carasik’s collection of the commentary of several medieval rabbis. Modern interpretations were read and discussed as well, including a chapter by John Toews on the Eden story and one by Hirsch Cohen on Noah’s drunkenness. Following many of these readings, we were asked to respond with brief online discussion board posts, which we would elaborate on in class. This first close reading uncovered many thematic elements of the Book of Genesis that we were able to expand upon and view from multiple perspectives. Some of our initial thoughts are summarized in the Findings section, below.</p>
                <p>Following our initial reading, we did a second close reading through collaborative XML encoding. In order to understand this part of our methodology, it is necessary to understand some basics about XML (eXtensible Markup Language).</p>
                <p>XML is similar in appearance to HTML. As with HTML, the mark-up is set between pointy brackets, and it appears within and around the text it is used to encode. However, while HTML provides instructions to internet browsers on how a text should be displayed or presented, XML describes a text’s structural and semantic features. For example, in HTML, the title of this essay, “Introductory Essay,” might be marked up as &lt;h1&gt;, for “heading 1,” instructing an internet browser to render it in large font:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;h1&gt;Introductory Essay&lt;/h1&gt;</p>
                <p>In XML, the same title might be marked as &lt;title&gt;:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;title&gt;Introductory Essay&lt;/title&gt;</p>
                <p>This XML markup conveys nothing about how “Introductory Essay” should be presented. Rather, it indicates something about the word’s semantic and structural relationship to the rest of the text. In this sense, XML can be used to add interpretive notes to a text, similar to how one writes comments in the margins of a print book or types them onto a Google Doc.</p>
                <p>However, a distinctive feature that sets XML apart from traditional methods of notetaking (and that XML shares with HTML), is how it conceives of text as a strict hierarchical structure. For example, a book may be divided into chapters, which may be divided into paragraphs, which may be divided into sentences. Generally speaking, this is observed as a strict sort of hierarchy or nesting: while chapters may contain paragraphs, and paragraphs may contain sentences, sentences cannot contain paragraphs, and paragraphs cannot contain chapters. In this sense, XML is “a formal model that is based on an ordered hierarchy, or, in technical informatic terms, a tree,” and this makes it a good choice for representing the structures of documents (Birnbaum).</p>
                <p>XML encodes these hierarchies by using “elements,” which cover a whole section of text and enclose it within a start tag and an end tag. For example, if one were to mark up a chapter of a book, the tags might look something like this: &lt;chapter&gt;[text of chapter]&lt;/chapter&gt;. Other elements can be encoded within larger ones, but strict nesting must be maintained; one could add the start tag &lt;paragraph&gt; to a paragraph in a chapter, but the end tag would have to be within the chapter as well. Here is an example of proper nesting:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;chapter&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;paragraph&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;/paragraph&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;/chapter&gt;</p>
                <p>Here is an example of incorrect nesting:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;chapter&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;paragraph&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;/chapter&gt;</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&lt;/paragraph&gt;</p>
                <p>Importantly, with XML every single part of a text -- every single word and punctuation mark -- must be encoded as a structural feature or as part of one. As we will describe in our Findings section, below, this sometimes onerous requirement is one of the things that made close reading with XML so useful in the end.</p>
                <p>Finally, it should be observed that although there are conventional, ready-made XML vocabularies or schemas -- that is, sets of agreed-upon terms that can be used to encode texts, along with rules about how those terms can be used -- our strategy was to create our own custom XML vocabulary or schema as we were encoding. The reason for this is that we were trying to break free from conventional ways of thinking about Genesis: just as we did not wish to be limited by the way previous editions had represented and conceived of Genesis, we did not wish to be limited by specific ideas about the structures of texts in general.</p>
                <p>During our XML close reading of Genesis, we began by encoding the text separately, as individuals, then brought together our structural analyses and schemas and eventually reconciled and combined them. This was a great deal of work, proceeding much more slowly than our initial close reading. We encoded just Chapters 1-3 and 6-9, and we were able to reach a consensus only on the latter group of chapters. However, by reexamining the text with XML, we found structural elements within the text, such as repeated phrases or chiastic structures, that we would have otherwise missed, and as we will show, we conceived of these structural elements in a way that we believe is original, at least in some important respects.</p>
                <p>The basis of this edition, which is the beginning or first installment of a new digital scholarly edition of Genesis, is the XML document we produced.</p>
                <h2>Findings</h2>
                <p>Compared with other analyses of the Flood story, our analysis is different in a few key ways. To understand the significance of our final conclusions, it is necessary to set them in relief against our initial hypotheses, arrived at through traditional close reading, as well as to compare them with the conclusions of previous scholars.</p>
                <p>As described in the Methods section above, our analysis of Genesis 6-9 began with a traditional close reading. As we engaged in this first reading, we discussed possible meanings and focused on the overall plot of the text. The plot of Genesis 6-9, like the plot of Genesis 1-2, seems to be full of internal contradictions. While Genesis 1 and 2 tell two separate creation stories, Genesis 6-9 seemingly tells two different flood stories, evident by the flood lasting both 40 and 150 days and by an inconsistent number of animals entering the ark. Having observed these contradictions, we then used outside sources to look at the text in a new perspective. Readings on the Documentary Hypothesis seemed to explain contradictory sections of the text. In fact, they encouraged us to look for additional discontinuities and to read Genesis 6-9 as a patchwork of historical artifacts rather than a unified work.</p> 
                <p>During our second close reading, using XML, we were tasked with reassessing and discerning any patterns, structural or thematic, that the text offered. It was at this point that we noticed that the numbers in the text— seven, forty, and one hundred fifty— seem to be in a distinct, intentional pattern.</p> 
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7 days (7:4, 7:10)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;40 days (7:4, 7:12, 7:17)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;150 days (7:24)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;150 days (8:3)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;40 days (8:6)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7 days (8:10, 8:12)</p>
                <p>As it turns out, we were far from the first to notice this pattern or to conclude that it suggests a chiastic structure. Once we noted those distinct markers, we looked for and found further chiastic parallels within the text. Our analysis seemed to focus on the more structural elements, including repeated words, phrases, and actions, as well as thematic parallels, like the theme of regret. We found that these parallels encouraged us to compare one part of the text with another, rather than read it from beginning to end. We also found that several parallels in the second half of the chiasm appear to be out of order, though they nevertheless seemed to clearly parallel sections from the first half of the chiasm.</p>
                <p>While the class agreed on how to define most parts of the chiasm, we had many debates as to what should be in the center, which in many ways is the most important part of the chiasm because the entire structure frames it. Most of us defined the center as 8:1-3, which centers on the phrase “God remembered Noah.” However, others argued for 7:21-23, which highlights almost the opposite: God’s nearly complete annihilation of all life. Emphasizing “God remembered Noah” highlights God as a merciful power and de-emphasizes God’s destructive tendencies and their consequences.</p>
                <p>This debate was eventually resolved through our overall XML reading of the text. It was clear to us that 7:17b-20 (in which the waters increase and cover the mountains) parallels 8:4-5 (in which the waters decrease, uncovering the mountains). It was equally clear that 7:24 (which references a span of 150 days) parallels 8:3b (which also references a span of 150 days). If we folded 7:21-23 into 7:24, as most of us at first wanted to, we would have a satisfying center to our chiasm:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:17b-20 (Waters increase, mountains covered)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:21-24 (God forgets and destroys, 150 days)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:1-3a (God remembers and preserves)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:3b (150 days)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:4-5 (waters decrease, mountains appear)</p>
                <p>However, when we did that, 7:21-24 and 8:3b were no longer so clearly parallel to each other.</p>
                <p>It was the exacting requirements of XML encoding that got us stuck on this point. But it was also the same requirements that suggested an alternative that made good hierarchical sense:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:17b-20 (Waters increase, mountains covered)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:21-24 (God forgets and destroys, 150 days)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:1-3 (God remembers and preserves, 150 days)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:4-5 (waters decrease, mountains appear)</p>
                <p>We considered the possibility that, rather than having a single unique item featured at the center, the chiasm might instead have two parallels, each of which could be broken down into two subsections. Within each of the central parallels, the first subsections were thematic inversions of each other (“God forgets and destroys” vs. “God remembers and preserves”), while the second subsections were direct parallels with each other (“150 days”). Structurally, this seemed to be an elegant solution. Thematically, it complicated everyone’s view in an interesting way, highlighting two of our main competing ideas about the meaning of the Flood story: the destructive and creative aspects of God, respectively.</p>
                <p>Further reading in the secondary literature strengthened our belief that we had analyzed the structure and thematic emphasis of the Flood story correctly. Previous scholarship has identified three smaller chiasms within the larger Chapter 6-9 chiasm we have identified. The first of these smaller chiasms occurs at 6:8-9 (Kikawada and Quinn 86), the second at 7:21-23a (Kikawada and Quinn 94-95), and the third at 9:6 (Kass 182-83). For context, one of them (6:8-9) is outlined below, in a manner that reflects the Hebrew word order:</p> 
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;Noah</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;found favor</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;in the eyes of the LORD</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;These are the generations of Noah</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;Noah was a righteous man</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;perfect he was</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;in his generations</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;with God</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;walked</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;Noah</p>
                <p>Because the parallel sections of these small chiasms are made up of phrases or even individual words or sounds, these chiasms are difficult or impossible to identify without knowledge of ancient Hebrew. However, knowledge of them affirmed the correctness of our analysis. Together, these small chiasms mark key points in our larger chiasm: one is placed near the beginning, one near the middle, and one near the end. Additionally, the fact that the middle chiasm centers on 7:21-24, where God forgets creation and destroys most of it, gave us the sense that the text was, if anything, giving that aspect of God extra emphasis, asking us not to ignore or smooth over God’s destructiveness. Finally, the specific small chiasm outlined above further emphasizes Noah as a righteous man, which in a way complicates Noah as a character because his righteousness in some ways parallels his drunkenness later in the story, suggesting a possible transformation of Noah’s character pre-flood and post-flood.</p> 
                <p>Something else we gained from our second dip into the scholarly literature was an understanding of the ways in which our analysis seems to be original. Specifically, the center of our larger Chapter 6-9 chiasm is different from any other analysis we know of. For example, Gordon J. Wenham, who formulated the most prominent chiastic theory of the Flood story, believes that the phrase “God remembered Noah” is at the center of the chiasm, as shown here:</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:19-20 (mountains covered)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;7:21-24 (150 days, waters prevail)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:1 (GOD REMEMBERS NOAH)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:3 (150 days, waters abate)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;8:4-5 (mountain tops visible)</p>
                <p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;(Wenham, qtd. in Kikawada and Quinn 108)</p>
                <p>According to Wenham, Genesis 6-9 centers on the conventionally pious notion of God remembering Noah, making the Noah story arc primarily about God’s mercy towards humanity, despite humanity committing grievous sins and succumbing to evil. From there, the story arc focuses on rebuilding and repopulating the Earth. But it seems Wenham is able to arrive at this conclusion because his methodology has not forced him to account for every line (let alone every word) of the text. Our analysis is more comprehensive, yielding a more complex center of the structure.</p>
                <p>Perceiving that the middle of our chiasm emphasizes two sides of God’s nature, we found that the emphasis of the Flood story arc is on God's destructive abilities just as much as his creative abilities -- a less forgiving picture of God. Thus, our analysis raises new questions about the Flood story and about God as a character.</p> 
                <h2>Conclusion</h2>
                <p>While we believe that we have reached new conclusions from our research, we must acknowledge that there are some limitations to our analysis. The major issue our team had was that the majority of us could read only English translations of Genesis. While we tried to limit our bias by using multiple translations, and the OJPS is a fairly literal version of the Bible, it is possible that we may have missed some crucial elements that may be obvious to scholars who read ancient Hebrew. Time was also a factor, since we had only a few months to put together this edition. Related to the time factor is the issue that our structural analysis is not as extensive as we had hoped, limited to just the Flood story (though we also did a less complete XML analysis of Chapters 1-3).</p>
                <p>Despite these limitations, we feel our newfound understanding of the chiastic structure of the Flood story is worth sharing. If the conclusions reached from our research are indeed true, they could have implications for future analysis of the text. Analysis of Genesis, along with the rest of the Bible, changes over time as new evidence arises. Our interpretation of the Flood story’s chiastic structure opens the door to a better understanding of emphasis as a tool of the author(s). Understanding emphasis allows readers to understand the purposes and themes of the text. We also believe our analysis supports the theory that Genesis was originally an oral text. The idea that Genesis was originally in a spoken form has its roots in the language of the text. As translators such as Robert Alter have observed, the writing sometimes reads like a song, with metrical rhythm (Alter xl-xlv). In addition, poetry often includes other methods of conveying structure and purpose, such as repetition and parallelism, which are among the main features of chiastic structure.</p>
                    <p>The future of this research allows for many different paths to be taken, but our team would likely prefer to continue studying the occurrences and uses of poetic and other semantic structures, including thematic structure, as a means of determining the intended meaning(s) of the text. In future semesters, different cohorts of students will build on what we have done, eventually (we hope) completing this digital scholarly edition of Genesis. We believe that this project will be particularly useful to undergraduate students and that it could potentially influence how Genesis is understood by a range of readers, from religious practitioners to secular scholars.</p>
                    </Page>
        </div>
    );
}

export default Introduction;